#define RPVersion _rpversion
#define SETPATHdll _setpathdll
#define ABFL1dll _abfl1dll
#define ABFL2dll _abfl2dll
#define ACTVYdll _actvydll
#define AGdll _agdll
#define CCRITdll _ccritdll
#define CP0dll _cp0dll
#define CRITPdll _critpdll
#define CSATKdll _csatkdll
#define CV2PKdll _cv2pkdll
#define CVCPKdll _cvcpkdll
#define CVCPdll _cvcpdll
#define DBDTdll _dbdtdll
#define DBFL1dll _dbfl1dll
#define DBFL2dll _dbfl2dll
#define DDDPdll _dddpdll
#define DDDTdll _dddtdll
#define DEFLSHdll _deflshdll
#define DHD1dll _dhd1dll
#define DHFL1dll _dhfl1dll
#define DHFLSHdll _dhflshdll
#define DIELECdll _dielecdll
#define DOTFILLdll _dotfilldll
#define DPDD2dll _dpdd2dll
#define DPDDKdll _dpddkdll
#define DPDDdll _dpdddll
#define DPDTKdll _dpdtkdll
#define DPDTdll _dpdtdll
#define DPTSATKdll _dptsatkdll
#define DSFLSHdll _dsflshdll
#define DSFL1dll _dsfl1dll
#define ENTHALdll _enthaldll
#define ENTROdll _entrodll
#define ESFLSHdll _esflshdll
#define FGCTYdll _fgctydll
#define FGCTY2dll _fgcty2dll
#define FUGCOFdll _fugcofdll
#define FPVdll _fpvdll
#define GERG04dll _gerg04dll
#define GETFIJdll _getfijdll
#define GETKTVdll _getktvdll
#define GIBBSdll _gibbsdll
#define HSFLSHdll _hsflshdll
#define INFOdll _infodll
#define LIMITKdll _limitkdll
#define LIMITSdll _limitsdll
#define LIMITXdll _limitxdll
#define MELTPdll _meltpdll
#define MELTTdll _melttdll
#define MLTH2Odll _mlth2odll
#define NAMEdll _namedll
#define PASSCMN _passcmn
#define PDFL1dll _pdfl1dll
#define PDFLSHdll _pdflshdll
#define PEFLSHdll _peflshdll
#define PHFL1dll _phfl1dll
#define PHFLSHdll _phflshdll
#define PHIXdll _phixdll
#define PHI0dll _phi0dll
#define PQFLSHdll _pqflshdll
#define PREOSdll _preosdll
#define PRESSdll _pressdll
#define PSFL1dll _psfl1dll
#define PSFLSHdll _psflshdll
#define PUREFLDdll _pureflddll
#define QMASSdll _qmassdll
#define QMOLEdll _qmoledll
#define RESIDUALdll _residualdll
#define REDXdll _redxdll
#define RMIX2dll _rmix2dll
#define SATDdll _satddll
#define SATEdll _satedll
#define SATGVdll _satgvdll
#define SATHdll _sathdll
#define SATPdll _satpdll
#define SATSdll _satsdll
#define SATTdll _sattdll
#define SATTPdll _sattpdll
#define SATSPLNdll _satsplndll
#define SETAGAdll _setagadll
#define SETKTVdll _setktvdll
#define SETMIXdll _setmixdll
#define SETMODdll _setmoddll
#define SETREFdll _setrefdll
#define SETUPdll _setupdll
#define SPLNVALdll _splnvaldll
#define SPLNROOTdll _splnrootdll
#define SUBLPdll _sublpdll
#define SUBLTdll _subltdll
#define SURFTdll _surftdll
#define SURTENdll _surtendll
#define TDFLSHdll _tdflshdll
#define TEFLSHdll _teflshdll
#define THERM0dll _therm0dll
#define THERM2dll _therm2dll
#define THERM3dll _therm3dll
#define THERMdll _thermdll
#define THFLSHdll _thflshdll
#define TPFLSHdll _tpflshdll
#define TPFL2dll _tpfl2dll
#define TPRHOdll _tprhodll
#define TQFLSHdll _tqflshdll
#define TRNPRPdll _trnprpdll
#define TSFLSHdll _tsflshdll
#define VIRBdll _virbdll
#define VIRCdll _vircdll
#define WMOLdll _wmoldll
#define MASSdll _massdll
#define MOLEdll _moledll
